version: '3.8'  

services:  
  web:    
    build:  
      context: . 
      dockerfile: Dockerfile
    environment:  
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      MAILING_EMAIL: ${MAILING_EMAIL}
      MAILING_EMAIL_PASSWORD: ${MAILING_EMAIL_PASSWORD}
      DATABASE_CONNECTION_STRING: Server=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:  
      - "8080:8080"
    networks:  
      - network
    depends_on:  
      - db 

  db:  
    image: postgres:latest
    container_name: postgres
    expose: 
      - "5432" 
    environment:  
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    
    volumes:  
      - pgdata:/var/lib/postgresql/data # Персистентное хранилище для данных базы
    networks:  
      - network

  pgadmin:  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}  
    ports:  
      - "1234:80"
    networks:  
      - network
    depends_on:  
      - db

networks:  
  network:  
    driver: bridge

volumes:  
  pgdata:
