version: '3.8'  

services:  
  web:    
    build:  
      context: . 
      dockerfile: Dockerfile   
    ports:  
      - "8080:8080"
    networks:  
      - network
    depends_on:  
      - db 

  db:  
    image: postgres:latest
    container_name: postgres
    expose: 
      - "5432" 
    environment:  
      POSTGRES_DB: Logistics 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin    
    volumes:  
      - pgdata:/var/lib/postgresql/data # Персистентное хранилище для данных базы
    networks:  
      - network

  pgadmin:  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:  
      - "1234:80"
    networks:  
      - network
    depends_on:  
      - db

networks:  
  network:  
    driver: bridge

volumes:  
  pgdata:
