version: '3.8'  

services:  
  web:    
    build:  
      context: . 
      dockerfile: Dockerfile   
    ports:  
      - "5169:8080"
    depends_on:  
      - db 

  db:  
    image: postgres:latest
    ports:  
      - "5432:5432" 
    environment:  
      POSTGRES_DB: Logistics 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin    
    volumes:  
      - pgdata:/var/lib/postgresql/data # Персистентное хранилище для данных базы  

volumes:  
  pgdata:
