name: Build and Deploy Docker Compose  

on:  
  push:  
    branches:  
      - main 
      
jobs:  
  build:  
    runs-on: self-hosted 
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Build and Start Services  
        run: |
          docker-compose down
          docker system prune -af
          docker-compose up -d --build
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MAILING_EMAIL: ${{ vars.MAILING_EMAIL }}
          MAILING_EMAIL_PASSWORD: ${{ secrets.MAILING_EMAIL_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
